/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'alpo' at '6/6/15 4:17 PM' with Gradle 1.12
 *
 * @author alpo, @date 6/6/15 4:17 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
